FROM fedora

RUN dnf -y install \
    make \
    automake \
    gcc \
    gcc-c++ \
    kernel-devel \
    re2c \
    bison \
    libxml2-devel \
    openssl \
    openssl-devel \
    wget \
    xz

WORKDIR /opt
