FROM alpine:3.7

RUN apk add --no-cache \
    wget \
    autoconf \
    dpkg-dev \
    dpkg \
    file \
    g++ \
    gcc \
    libc-dev \
    make \
    pcre-dev \
    pkgconf \
    re2c \
    tar \
    xz \
    bison \
    libxml2-dev \
    libressl-dev \
    sqlite-dev \
    libpng-dev \
    freetype-dev \
    oniguruma-dev \
    vim \
    cmake \
    git \
    && mkdir -p /opt

WORKDIR /opt
