FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    apt-utils \
    wget \
    xz-utils \
    build-essential \
    bison \
    re2c \
    libxml2-dev \
    libssl-dev \
    libpcre++-dev \
    libsqlite3-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libdb5.3++-dev \
    libdb-dev \
    libsslcommon2-dev \
    pkg-config \
    libtokyocabinet-dev \
    libenchant-dev \
    libwebp-dev \
    libjpeg-dev \
    libpng-dev \
    libxpm-dev \
    libfreetype6-dev \
    libgmp-dev \
    libc-client-dev \
    libkrb5-dev \
    libldap2-dev \
    libsasl2-dev \
    libodbc1 \
    unixodbc-dev \
    libpq-dev \
    libpspell-dev \
    libedit-dev \
    librecode-dev \
    libsnmp-dev \
    libtidy-dev \
    libxslt-dev \
    libgdbm-dev \
    freetds-dev \
    libzip-dev \
    firebird-dev \
    && mkdir -p /opt

WORKDIR /opt
