FROM ubuntu

RUN apt-get update && apt-get install -y \
    wget \
    xz-utils \
    build-essential \
    libxml2-dev \
    libssl-dev \
    libpcre++-dev \
    libsqlite3-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libdb5.3++-dev \
    libdb-dev
