FROM ubuntu

RUN apt-get update && apt-get install -y \
    apt-utils \
    wget \
    xz-utils \
    build-essential \
    autoconf \
    re2c \
    bison \
    libxml2-dev \
    libssl-dev \
    libpcre++-dev \
    libsqlite3-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libdb5.3++-dev \
    libdb-dev \
    libenchant-dev \
    libpng-dev \
    libgmp-dev \
    libc-client-dev \
    libkrb5-dev \
    libjpeg-dev \
    libxpm-dev \
    libfreetype6-dev \
    libldap2-dev \
    unixodbc-dev \
    libodbc1 \
    freetds-dev \
    libsnmp-dev \
    snmp

WORKDIR /opt
