FROM fedora:39

RUN dnf -y upgrade --refresh && dnf -y install \
    vim \
    make \
    automake \
    gcc \
    gcc-c++ \
    kernel-devel \
    re2c \
    bison \
    libxml2-devel \
    openssl-devel \
    wget \
    xz \
    systemtap-sdt-devel \
    sqlite-devel \
    bzip2-devel \
    libcurl-devel \
    enchant2-devel \
    libpng-devel \
    libavif-devel \
    libwebp-devel \
    libjpeg-devel \
    libXpm-devel \
    freetype-devel \
    gmp-devel \
    oniguruma-devel \
    aspell-devel \
    libedit-devel \
    net-snmp-devel \
    libsodium-devel \
    libargon2-devel \
    libtidy-devel \
    libzip-devel \
    cmake

WORKDIR /opt
