FROM centos:6

RUN yum install -y \
    gcc \
    git \
    libmemcached-dev \
    zlib-devel \
    wget \
    vim \
    xz \
    m4 \
    bison \
    libxml2-devel \
    make \
    autoconf \
    file

WORKDIR /opt
